# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:54
from __future__ import unicode_literals

import core.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            bases=(core.mixins.LocationMixin, models.Model),
        ),
    ]
