# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-28 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subway',
            name='coordinates',
        ),
    ]
