# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 21:54
from __future__ import unicode_literals

import core.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('subway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Subway')),
            ],
            bases=(core.mixins.LocationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('avatar', models.ImageField(upload_to='')),
                ('about', models.CharField(max_length=256)),
                ('date_join', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='users',
            field=models.ManyToManyField(to='core.User'),
        ),
    ]
