# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-28 17:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 3, 28, 17, 20, 59, 8791, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
