# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160805_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='users',
        ),
        migrations.AddField(
            model_name='meeting',
            name='members',
            field=models.ManyToManyField(related_name='favorite_meetings', to='core.User'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to='core.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='subway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='location.Subway'),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
