# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meeting_meeting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_slug', models.CharField(max_length=16)),
                ('external_id', models.PositiveIntegerField()),
                ('token', models.CharField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='group_type',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='socialdata',
            unique_together=set([('social_slug', 'external_id')]),
        ),
    ]
