# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170402_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
