# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-11 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170211_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphotos',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
