# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-19 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170211_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userphotos',
            options={'ordering': ['-is_avatar']},
        ),
        migrations.RenameField(
            model_name='userphotos',
            old_name='user',
            new_name='owner',
        ),
    ]
