# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-16 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170409_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_type',
            new_name='category',
        ),
    ]
