# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170416_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_key',
            field=models.CharField(default='2017-05-02 20:14:51.757789+00:00', max_length=256),
            preserve_default=False,
        ),
    ]
