# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-22 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170416_1323'),
        ('chat', '0002_auto_20170402_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='channel_slug',
            field=models.CharField(db_index=True, default='2017-04-22 16:50:57.871021', max_length=128, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.Meeting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='my_own_chats', to='core.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chats_with_me', to='core.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Chat'),
        ),
    ]
