# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-04 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_confirm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='confirm',
            unique_together=set([('meeting', 'user')]),
        ),
    ]
