# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-23 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20170422_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
